name: dockerhub-ratelimit-exporter
blobstore:
  provider: s3
  options:
    bucket_name: dockerhub-ratelimit-exporter-boshrelease
    region: ap-northeast-1
    endpoint: https://s3-ap-northeast-1.amazonaws.com
